apiVersion: v2
type: application
appVersion: 1.0.0
description: Plex Media Server with autoskip, autoscan, and optional OnePasswordItem secrets sync.
name: plex
version: 1.0.0
kubeVersion: ">=1.22.0-0"
keywords:
  - plex
  - plex-media-server
home: https://charts.gabe565.com/charts/plex/
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
sources:
  - https://github.com/gabe565/charts/tree/main/charts/plex
  - https://hub.docker.com/r/linuxserver/plex
maintainers: []
dependencies:
  - name: plex
    version: "0.5.1"
    repository: https://charts.gabe565.com
  - name: plex-auto-skip
    alias: skip
    version: "0.0.5"
    repository: https://expectedbehaviors.github.io/plex-autoskip-helm-chart
  - name: app-template
    alias: autoscan
    version: "4.6.2"
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: onepassworditem
    version: "1.1.1"
    repository: https://expectedbehaviors.github.io/OnePasswordItem-helm
